name: Test

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.23.x
          - 1.24.x
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Get dependencies
        run: go mod download
      - name: Test
        run: go test -v -race ./...
